name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Astro app
        run: npm run build

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' < package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        env:
          CR_TOKEN: ${{ secrets.CR_TOKEN }}
        run: echo "${{ secrets.CR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build and push production image
      - name: Build and Push Docker Image for Production
        run: |
          docker build \
            --build-arg CONFIGURATION=production \
            -t ghcr.io/${{ github.repository }}:${{ env.VERSION }} \
            -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository }}:latest
